slsnrnsep/Hanghae99-Finalproject-Backend-Baseballmate

src/main/java/com/finalproject/backend/baseballmate/config/DbSetConfig.java, src/main/java/com/finalproject/backend/baseballmate/controller/GoodsCommentController.java, src/main/java/com/finalproject/backend/baseballmate/model/GoodsComment.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsCommentService.java, src/main/resources/application.properties
=> [Fix] : 굿즈코멘트 등록, 수정, 삭제 유저만

build.gradle, src/main/java/com/finalproject/backend/baseballmate/controller/PhoneController.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/PhoneRequstDto.java, src/main/java/com/finalproject/backend/baseballmate/service/PhoneService.java
=> [Add] : 회원 문자인증

src/main/java/com/finalproject/backend/baseballmate/controller/PhoneController.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/PhoneRequstDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/PhoneResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/PhoneService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java
=> [Fix] : 회원 문자인증

src/main/java/com/finalproject/backend/baseballmate/controller/GoodsCommentLikesController.java, src/main/resources/application.properties
=> [Fix] : 굿즈 댓글좋아요  수정

.idea/dataSources.xml, src/main/java/com/finalproject/backend/baseballmate/OAuth2/KakaoOAuth2.java, src/main/java/com/finalproject/backend/baseballmate/controller/GoodsController.java, src/main/java/com/finalproject/backend/baseballmate/controller/UserContorller.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/GoodsRequestDto.java, src/main/java/com/finalproject/backend/baseballmate/security/JwtTokenProvider.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java, src/main/resources/application.properties, src/main/resources/static/index.html
=> [Add] : 카카오톡 프로필사진 받아오기

src/main/java/com/finalproject/backend/baseballmate/controller/ScreenController.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/AllScreenResponseDto.java
=> [Fix] : 스크린야구 파일생성

src/main/java/com/finalproject/backend/baseballmate/controller/ScreenCommentController.java, src/main/java/com/finalproject/backend/baseballmate/controller/ScreenLikesController.java, src/main/java/com/finalproject/backend/baseballmate/model/Screen.java, src/main/java/com/finalproject/backend/baseballmate/model/ScreenComment.java, src/main/java/com/finalproject/backend/baseballmate/model/ScreenCommentLikes.java, src/main/java/com/finalproject/backend/baseballmate/model/ScreenLikes.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenCommentRepository.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenLikesRepository.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/ScreenCommentRequestDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/ScreenDetailResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenCommentService.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenLikesService.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenService.java
=> [Add] : 스크린야구 코멘트 , 좋아요

src/main/java/com/finalproject/backend/baseballmate/controller/GroupController.java, src/main/java/com/finalproject/backend/baseballmate/controller/ScreenCommentLikesController.java, src/main/java/com/finalproject/backend/baseballmate/model/ScreenComment.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenCommentLikesRepository.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/UserRequestDto.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenCommnetLikesService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java
=> [Add] : 스크린야구 코멘트좋아요

src/main/java/com/finalproject/backend/baseballmate/controller/ScreenController.java, src/main/java/com/finalproject/backend/baseballmate/model/Screen.java, src/main/java/com/finalproject/backend/baseballmate/model/ScreenApplication.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenApplicationRepository.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java, src/main/resources/application.properties
=> [Add] : 스크린야구 참가신청, 취소

src/main/java/com/finalproject/backend/baseballmate/controller/ScreenController.java, src/main/java/com/finalproject/backend/baseballmate/model/CanceledScreenList.java, src/main/java/com/finalproject/backend/baseballmate/model/Screen.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/repository/CanceledScreenListRepository.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenApplicationRepository.java, src/main/java/com/finalproject/backend/baseballmate/security/JwtAuthenticationFilter.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java, src/main/resources/application.properties
=> [Fix] : 스크린야구 참가신청, 취소

src/main/java/com/finalproject/backend/baseballmate/repository/ScreenLikesRepository.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenLikesService.java
=> [Fix] : 스크린야구 좋아요 수정

src/main/java/com/finalproject/backend/baseballmate/model/ScreenComment.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenCommentService.java
=> [Add] : 스크린야구 댓글 프로필 사진

src/main/java/com/finalproject/backend/baseballmate/repository/ScreenCommentLikesRepository.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenCommnetLikesService.java
=> [Fix] : 스크린야구 댓글 좋아요

src/main/java/com/finalproject/backend/baseballmate/controller/MypageController.java, src/main/java/com/finalproject/backend/baseballmate/controller/ScreenController.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenApplicationRepository.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenRepository.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/AllScreenResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenService.java
=> [Add] : 스크린야구 마이페이지 조회

src/main/java/com/finalproject/backend/baseballmate/controller/GoodsController.java, src/main/java/com/finalproject/backend/baseballmate/model/Goods.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/GoodsRequestDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/AllGoodsResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/GoodsDetailResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsService.java
=> [Fix] : 굿즈 생성 수정

src/main/java/com/finalproject/backend/baseballmate/OAuth2/KakaoOAuth2.java, src/main/java/com/finalproject/backend/baseballmate/controller/GoodsController.java, src/main/java/com/finalproject/backend/baseballmate/model/Goods.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/GoodsRequestDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/AllGoodsResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsService.java
=> [Fix] : 굿즈 이미지 생성, 카카오 로그인 수정

src/main/java/com/finalproject/backend/baseballmate/controller/AlarmController.java, src/main/java/com/finalproject/backend/baseballmate/model/Alarm.java, src/main/java/com/finalproject/backend/baseballmate/repository/AlarmRepository.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/AlarmRequestDto.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/AlarmSaveDto.java, src/main/java/com/finalproject/backend/baseballmate/service/AlarmService.java, src/main/java/com/finalproject/backend/baseballmate/service/GroupService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java, src/main/resources/application.properties
=> [Fix] : 알람기능

src/main/java/com/finalproject/backend/baseballmate/chat/EmbeddedRedisConfig.java, src/main/java/com/finalproject/backend/baseballmate/controller/MainController.java, src/main/java/com/finalproject/backend/baseballmate/controller/ScreenController.java, src/main/java/com/finalproject/backend/baseballmate/model/Goods.java, src/main/java/com/finalproject/backend/baseballmate/model/GoodsComment.java, src/main/java/com/finalproject/backend/baseballmate/model/GoodsLikes.java, src/main/java/com/finalproject/backend/baseballmate/model/User.java, src/main/java/com/finalproject/backend/baseballmate/repository/GoodsCommentRepository.java, src/main/java/com/finalproject/backend/baseballmate/repository/GoodsLikesRepository.java, src/main/java/com/finalproject/backend/baseballmate/repository/GroupRepository.java, src/main/java/com/finalproject/backend/baseballmate/repository/ScreenRepository.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/AllGoodsResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/HotScreenResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsService.java, src/main/java/com/finalproject/backend/baseballmate/service/ScreenService.java
[Add] : 굿즈 메인 댓글, 좋아요 / 스크린 인기순, 최신순 조회
=> [Add] : 굿즈 메인 댓글, 좋아요 / 스크린 인기순, 최신순 조회

src/main/java/com/finalproject/backend/baseballmate/model/Community.java, src/main/java/com/finalproject/backend/baseballmate/model/Goods.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/AllGoodsResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/responseDto/HotScreenResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/service/CommunityService.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java
=> [Add] : 커뮤니티 , 굿즈에 팀 , 주소 추가

src/main/java/com/finalproject/backend/baseballmate/model/Alarm.java, src/main/java/com/finalproject/backend/baseballmate/service/AlarmService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java
=> [Fix] : 알람삭제문제 해결

src/main/java/com/finalproject/backend/baseballmate/controller/GoodsController.java, src/main/java/com/finalproject/backend/baseballmate/controller/GoodsLikesController.java, src/main/java/com/finalproject/backend/baseballmate/groupChat/ChatRoomCreateResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/groupChat/ChatRoomResponseDto.java, src/main/java/com/finalproject/backend/baseballmate/join/JoinRequestsService.java, src/main/java/com/finalproject/backend/baseballmate/model/GoodsLikes.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsLikesService.java, src/main/java/com/finalproject/backend/baseballmate/service/GoodsService.java, src/main/java/com/finalproject/backend/baseballmate/service/UserService.java, src/main/resources/application.properties
=> [Fix] : 굿즈 좋아요 아이디값 추가

src/main/java/com/finalproject/backend/baseballmate/controller/CommunityCommentController.java, src/main/java/com/finalproject/backend/baseballmate/repository/CommunityCommentRepository.java, src/main/java/com/finalproject/backend/baseballmate/requestDto/AllCommunityDto.java, src/main/java/com/finalproject/backend/baseballmate/security/OAuth2/KakaoOAuth2.java, src/main/java/com/finalproject/backend/baseballmate/service/CommunityCommentService.java, src/main/java/com/finalproject/backend/baseballmate/service/CommunityService.java, src/main/resources/application.properties
[Fix] : 굿즈 댓글 수정 / 삭제 , 커뮤니티 시간 삽입
=> [Fix] : 굿즈 댓글 수정 / 삭제 , 커뮤니티 시간 삽입
